name: Parent CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java (Child Action)
        uses: ./.github/actions/setup-java

      - name: Build Project (Child Action)
        uses: ./.github/actions/maven-build
