name: Assignment-pipeline

on: [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Stage
        run: |
          echo " Validate stage."

  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan
        run: |
          echo "Scan stage."

  deploy-pre-request:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Code Scanning
        run: |
          echo "Scanning stage."

  deploy:
    runs-on: ubuntu-latest
    needs: deploy-pre-request
    steps:
      - name: Deploy
        run: |
          echo "Deploy stage."
